# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 07:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Face',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('image', models.FileField(upload_to=b'')),
                ('message', models.CharField(max_length=200)),
            ],
        ),
    ]
