# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='face',
            name='image',
        ),
        migrations.AddField(
            model_name='face',
            name='image_1',
            field=models.FileField(blank=True, default=None, null=True, upload_to=b''),
        ),
        migrations.AddField(
            model_name='face',
            name='image_2',
            field=models.FileField(blank=True, default=None, null=True, upload_to=b''),
        ),
        migrations.AddField(
            model_name='face',
            name='image_3',
            field=models.FileField(blank=True, default=None, null=True, upload_to=b''),
        ),
    ]
