# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0002_auto_20161125_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='face',
            name='image_1',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='face',
            name='image_2',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='face',
            name='image_3',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=b''),
        ),
    ]
