# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-23 05:30
from __future__ import unicode_literals

from django.db import migrations, models
import finding.models


class Migration(migrations.Migration):

    dependencies = [
        ('finding', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='findimage',
            name='image_upload',
            field=models.ImageField(upload_to=finding.models.get_upload_to),
        ),
    ]
